(function() {
    var node = $("<div>").addClass("section dark white osl big").attr("id", "links-section").css("height", "40vh").css("padding-top", "10px").appendTo($(document.body));
    node.append($("<div>")
        .addClass("container-fluid")
        .append($("<div>")
            .addClass("col-md-4"))
        .append($("<div>")
            .addClass("col-md-2")
            .append($("<a>")
                .attr("href", "license.html")
                .html("License")))
        .append($("<div>")
            .addClass("col-md-2")
            .append($("<a>")
                .attr("href", "privacy.html")
                .html("Privacy")))
        .append($("<br>"))
        .append($("<div>")
            .addClass("col-md-4"))
        .append($("<div>")
            .addClass("col-md-2")
            .append($("<a>")
                .attr("href", "about.html")
                .html("About")))
        .append($("<div>")
            .addClass("col-md-2")
            .append($("<a>")
                .attr("href", "https://github.com/ethan2-0/RollCall")
                .html("Source (github)")))
        .append($("<br>"))
        .append($("<div>")
            .addClass("col-md-4"))
        .append($("<div>")
            .addClass("col-md-2")
            .append($("<a>")
                .attr("href", "index.html")
                .html("Home"))))
})();